// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pakar.Infrastructure.Persistence;

#nullable disable

namespace Pakar.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005134755_SqliteInitialSchema")]
    partial class SqliteInitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Pakar.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pakar.Domain.Entities.Camera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastActiveTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("Pakar.Domain.Entities.Detection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BoundingBoxJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("TEXT");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<string>("SnapshotUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpotExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SpotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("SpotId");

                    b.ToTable("Detections");
                });

            modelBuilder.Entity("Pakar.Domain.Entities.ParkingSpot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Spots");
                });

            modelBuilder.Entity("Pakar.Domain.Entities.ParkingZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Pakar.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpotId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Pakar.Domain.Entities.SavedZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ZoneId");

                    b.ToTable("SavedZones");
                });

            modelBuilder.Entity("Pakar.Domain.Entities.Camera", b =>
                {
                    b.HasOne("Pakar.Domain.Entities.ParkingZone", "Zone")
                        .WithMany("Cameras")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Pakar.Domain.Entities.Detection", b =>
                {
                    b.HasOne("Pakar.Domain.Entities.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pakar.Domain.Entities.ParkingSpot", "Spot")
                        .WithMany()
                        .HasForeignKey("SpotId");

                    b.Navigation("Camera");

                    b.Navigation("Spot");
                });

            modelBuilder.Entity("Pakar.Domain.Entities.ParkingSpot", b =>
                {
                    b.HasOne("Pakar.Domain.Entities.ParkingZone", "Zone")
                        .WithMany("Spots")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Pakar.Domain.Entities.Report", b =>
                {
                    b.HasOne("Pakar.Domain.Entities.ParkingSpot", "Spot")
                        .WithMany("Reports")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pakar.Domain.Entities.AppUser", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pakar.Domain.Entities.SavedZone", b =>
                {
                    b.HasOne("Pakar.Domain.Entities.AppUser", "User")
                        .WithMany("SavedZones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pakar.Domain.Entities.ParkingZone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Pakar.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("SavedZones");
                });

            modelBuilder.Entity("Pakar.Domain.Entities.ParkingSpot", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Pakar.Domain.Entities.ParkingZone", b =>
                {
                    b.Navigation("Cameras");

                    b.Navigation("Spots");
                });
#pragma warning restore 612, 618
        }
    }
}
